repos:
  - name: source
    location: https://github.com/nicholasdille/Sessions

services:
  - name: dind
    image: docker:stable-dind
    privileged: true

steps:

  - name: build
    image: openjdk:8-jdk
    commands:
      - cd containers/020_multi_stage/01_separation
      - javac HelloWorld.java

  - name: build
    image: openjdk:8-jre
    commands:
      - cd containers/020_multi_stage/01_separation
      - java HelloWorld

  - name: package
    image: docker:stable
    environment:
      - DOCKER_HOST=tcp://dind:2375
    commands:
      - cd containers/020_multi_stage/01_separation
      - docker build --tag hello-world-java .

  - name: test
    image: docker:stable
    environment:
      - DOCKER_HOST=tcp://dind:2375
    commands:
      - docker run hello-world-java