repos:
  - name: source
    location: https://github.com/nicholasdille/Sessions

files:
  - inject: Dockerfile
    content: |-
      FROM openjdk:8-jre
      COPY HelloWorld.class
      CMD [ "java", "HelloWorld" ]

services:
  - name: dind
    image: docker:stable-dind
    privileged: true
    suppress_log: true

steps:

  - name: build
    image: openjdk:8-jdk
    commands:
      - javac containers/020_advanced/020_multi_stage/01_separation/HelloWorld.java
      - jar cf HelloWorld.jar HelloWorld.class

  - name: test
    image: openjdk:8-jre
    commands:
      - java HelloWorld
      - java -jar HelloWorld.jar

  - name: package
    image: docker:stable
    environment:
      - DOCKER_HOST=tcp://dind:2375
    commands:
      - docker build --tag hello-world-java .

  - name: integration
    image: docker:stable
    environment:
      - DOCKER_HOST=tcp://dind:2375
    commands:
      - docker run hello-world-java